#! /bin/bash -eu
# Assumes bash 3.2 and later

# Export certificate to PEM file from trust store

binDir="$(dirname "${0}")"

# define util functions
# shellcheck source=./utils
source "${binDir}/utils"

packageHome="${packageHome:-/usr/share/java/bondolo.keystore/}"
defines=""


usage() {
        echo "# ${0} - Export certificate to PEM file from trust store"
        echo "# ${0} - [-?|-help] [-D<name>[=<value>] ...] <alias> <trustpath> <pempath>"
        echo "# "
        echo "# Options"
        echo "#   [-help | -?]              This help message"
        echo "#   [-D<name>[=<value>]]      Define a Java system property passed to JVM"
        echo "# "
        echo "# Arguments"
        echo "#    <alias>       certificate alias to be exported"
        echo "#    <trustpath>   File path of trust store for certificate storage"
        echo "#    <pempath>     File path for certificate in PEM format"
        echo "# "
        echo "# Environment Variables"
        echo "#   HOME                 Home directory"
        echo "# "
        echo "# "
}

for i in "${@:-}"; do
    case $i in
        -\?|-help)
            usage
            exit 0
            ;;
        -D*) defines="${defines:-} ${i}"; shift;;
        --) shift; break;;
        *) break;;
    esac
done

# Make sure there are three arguments
if [ "${#}" != "3" ]; then
  fatal 1 "Expected three arguments: <alias> <pempath> <trustpath>"
fi

# Set up default java options
options="-Xms32m -Xmx48m -Djava.security.egd=file:/dev/./urandom"

# Add in user defines
options="${options} ${defines}"

# Set up logging
if [ -d /mnt/XDATA/data ]; then
    logDir="/mnt/XDATA/data/regulus/var/log"
else
    logDir="${packageHome}/log"
fi
mkdir -p "${logDir}" || fatal $? "Failed to create log directory"

CLASSPATH=$(classpath "${packageHome}/libs")

# shellcheck disable=SC2116,SC2086
java ${JAVA_OPTS:-} ${options} -classpath "${CLASSPATH}" org.bondolo.keystore.libexec.CertExport "${@}"

